### ISSUE TITLE
Poll suggest: ja oder nein?

### ISSUE THREAD

**Issue by L-MzK** [FU-Hagen-Discord/epikur#4]
Damit könnten Mitglieder Serverumfragen vorschlagen, die in einem ModChannel landen und man lediglich kopieren/einfügen braucht, um eine Umfrage für alle Mitglieder zu machen.
💡 Serverumfragen gibt es bei Mathe/Info wöchentlich in einem extraChannel.

_Die Funktion könnte man einfach "freischalten", weil sie in dem Code zur Umfragefunktion schon beinhaltet ist, lediglich "deaktiviert"._

**Comment by R1taP** [comment]
Ja, gerne!

**Comment by dnns01** [comment]
Wenn ein entsprechender Channel besteht, kann das gerne reingenommen werden

**Comment by L-MzK** [comment]
Ja, das wäre nicht so der Umstand, einen Extra-Channel hinzufügen ^^ muss @R1taP sagen, ob sie das durchziehen möchte oder man lieber noch auf die Rückmeldung der drei anderen Mods wartet.
